### ISSUE TITLE
Exact versions of apr and apr-util

### ISSUE THREAD

**Issue by n30m1nd** [hannob/apache-uaf#2]
Hello, I have been trying a few hours already and no UAF's or ASAN errors are coming up. Most likely a problem exists between computer and chair but, would you mind sharing the exact versions of also, apr and apr-util that you used to reproduce?
Here's the versions I'm using:
* apr-1.6.5
* apr-util-1.6.1
* nghttp2-1.36.0
* Apache httpd 2.4.37

I have also tried pre-pending the http/2 preface to the ```/dev/urandom``` "fuzz" as follows:
```
$ xxd preface.txt
00000000: 5052 4920 2a20 4854 5450 2f32 2e30 0d0a  PRI * HTTP/2.0..
00000010: 0d0a 534d 0d0a 0d0a 0a                   ..SM.....
```

```bash
for x in $(seq 1 10000); do for i in $(seq 1 500); do head -n 50 /dev/urandom | cat preface.txt - | nc 127.0.0.1 80 & done; sleep 1; done
```

Thank you for your time!

**Comment by hannob** [comment]
We tested with all latest versions, but we also experienced highly unreliable results.

We have some newer results with a reliable reproducer and one bug got fixed, but we'll share that after the next apache release.
